/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import banco.Conexao;
import java.awt.Color;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juci reis
 */
public class TelaInicial extends javax.swing.JFrame {

    public static String email = "";
    public static String usu = "";
    public static String pw = "";
    public static int id = 0;
    public static int idUsu = 0;
    
    public static String restauranteNome = "";
    public static String desc = "";
    public static String valor = "";
    

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();

        txtUsuario.setText("E-mail");
        txtUsuario.setForeground(Color.GRAY);
        txtSenha.setText("Senha");
        txtSenha.setForeground(Color.GRAY);
        pwSenha.setVisible(false);

        btEntrar.requestFocus();

        lbObrigatorio.setVisible(false);
        lbObrigatorio1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbObrigatorio1 = new javax.swing.JLabel();
        lbObrigatorio = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        pwSenha = new javax.swing.JPasswordField();
        lbNovaConta = new javax.swing.JLabel();
        btEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(null);

        lbObrigatorio1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbObrigatorio1.setForeground(new java.awt.Color(255, 0, 0));
        lbObrigatorio1.setText("*");
        lbObrigatorio1.setToolTipText("CAMPO OBRIGATÓRIO");
        jPanel1.add(lbObrigatorio1);
        lbObrigatorio1.setBounds(210, 270, 10, 14);

        lbObrigatorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbObrigatorio.setForeground(new java.awt.Color(255, 0, 0));
        lbObrigatorio.setText("*");
        lbObrigatorio.setToolTipText("CAMPO OBRIGATÓRIO");
        jPanel1.add(lbObrigatorio);
        lbObrigatorio.setBounds(210, 200, 10, 14);

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)));
        txtSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSenha.setOpaque(false);
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });
        txtSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSenhaMouseClicked(evt);
            }
        });
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenha);
        txtSenha.setBounds(70, 260, 130, 30);

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)));
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsuario.setOpaque(false);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(70, 190, 130, 30);

        pwSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)));
        pwSenha.setOpaque(false);
        pwSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwSenhaFocusLost(evt);
            }
        });
        pwSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(pwSenha);
        pwSenha.setBounds(70, 260, 130, 30);

        lbNovaConta.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbNovaConta.setForeground(new java.awt.Color(255, 255, 255));
        lbNovaConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNovaConta.setText("Criar uma nova conta?");
        lbNovaConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNovaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNovaContaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbNovaContaMousePressed(evt);
            }
        });
        jPanel1.add(lbNovaConta);
        lbNovaConta.setBounds(70, 310, 130, 15);

        btEntrar.setText("ENTRAR");
        btEntrar.setBorder(new javax.swing.border.MatteBorder(null));
        btEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btEntrar);
        btEntrar.setBounds(80, 330, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TelaInicial.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 260, 443);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(260, 443));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbNovaContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNovaContaMouseClicked

    }//GEN-LAST:event_lbNovaContaMouseClicked

    private void lbNovaContaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNovaContaMousePressed
        telas.TelaNovaConta Tela = new telas.TelaNovaConta();
        Tela.setVisible(true);
    }//GEN-LAST:event_lbNovaContaMousePressed

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked

    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void pwSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwSenhaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if (txtUsuario.getText().equals("E-mail")) {
            if (txtUsuario.getForeground() == Color.GRAY) {
                txtUsuario.setText("");
                txtUsuario.setForeground(Color.BLACK);
            }
        }
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if (txtUsuario.getText().equals("")) {
            txtUsuario.setText("E-mail");
            txtUsuario.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void pegaId(String email) throws Exception{
   
        String txtSQL = "";
        
        Conexao con = new Conexao();
        con.getConexao();
        
        txtSQL = "select idCliente from vw_emailcliente where email = '" + email + "';";
                
        
        Statement banco = (Statement) Conexao.conexao.createStatement();
        
        ResultSet result = banco.executeQuery(txtSQL);
        
        while(result.next()){  
            
            idUsu = result.getInt("idCliente");
           
        }
        
     
        
    
        
    }
    
    
    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        try {
            pegaId(txtUsuario.getText());
        } catch (Exception ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (txtUsuario.getText().equals("E-mail")) {
            if (txtUsuario.getForeground() == Color.GRAY) {
                lbObrigatorio.setVisible(true);
            } else {
                lbObrigatorio.setVisible(false);
            }
        } else {
            lbObrigatorio.setVisible(false);
        }

        try {
            validaEmail(txtUsuario.getText());
            if (email != "") {
                confirmaSenha(String.valueOf(pwSenha.getPassword()));
                if (pw.equals(String.valueOf(pwSenha.getPassword()))) {
                    if (id == 1) {
                        telas.Telaadd Tela = new telas.Telaadd();
                        Tela.setVisible(true);
                    }
                    if (id == 2) {
                         
                    }
                  if (id == 3) {
                        telas.TelaClienteInicial Tela = new telas.TelaClienteInicial();
                        Tela.setVisible(true);
                        this.dispose();
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Senha incorreta");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "E-mail inexistente");
            }
        } catch (Exception ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        pwSenha.setText("");
        txtUsuario.setText("");

    }//GEN-LAST:event_btEntrarActionPerformed

    static void validaEmail(String usuario) throws Exception {

        Conexao con = new Conexao();
        con.getConexao();

        String txtSQL = "";

        txtSQL = "select * from tb_Usuario where Email = '" + usuario + "';";

        Statement banco = (Statement) Conexao.conexao.createStatement();
        ResultSet result = banco.executeQuery(txtSQL);

        while (result.next()) {

            email = result.getString("Email");
        }

    }

    static void confirmaSenha(String password) throws Exception {
        String[] pwss = {"", "", ""};

        Conexao con = new Conexao();
        con.getConexao();

        String txtSQL = "";

        txtSQL = "select * from tb_Usuario where Email = '" + email + "' and Senha  = '" + password + "'; ";

        Statement banco = (Statement) Conexao.conexao.createStatement();
        ResultSet result = banco.executeQuery(txtSQL);

        while (result.next()) {
            pw = result.getString("Senha");
            id = result.getInt("idTipo_Usu");
        }
    }


    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        if (txtSenha.getText().equals("Senha")) {
            if (txtSenha.getForeground() == Color.GRAY) {
                pwSenha.setVisible(true);
                pwSenha.requestFocus();
                txtSenha.setVisible(false);
            }
        }
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost

    }//GEN-LAST:event_txtSenhaFocusLost

    private void txtSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenhaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaMouseClicked

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void pwSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwSenhaFocusLost
        if (String.valueOf(pwSenha.getPassword()).isEmpty()) {
            txtSenha.setVisible(true);

        }
    }//GEN-LAST:event_pwSenhaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNovaConta;
    private javax.swing.JLabel lbObrigatorio;
    private javax.swing.JLabel lbObrigatorio1;
    private javax.swing.JPasswordField pwSenha;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
