/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import banco.Conexao;
import java.awt.Color;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.or;
import javax.swing.JOptionPane;

/**
 *
 * @author juci_reis-junior
 */
public class TelaNovaConta extends javax.swing.JFrame {

    public String email = "";
    public int TipoUsu = 3;
    public int Ponto = 0;
    public int idUsu = 0;

    /**
     * Creates new form TelaNovaConta
     */
    public TelaNovaConta() {
        initComponents();
        txtUsuario.setText("Usuário");
        txtUsuario.setForeground(Color.gray);

        txtEmail.setText("E-mail");
        txtEmail.setForeground(Color.GRAY);

        pwSenha.setVisible(false);
        txtSenha1.setText("Senha");
        txtSenha1.setForeground(Color.gray);

        txtTelefone.setText("");
        txtTelefone.setVisible(false);
        txtTelefone1.setText("Telefone");
        txtTelefone1.setForeground(Color.gray);

        btCadastro.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTelefone = new javax.swing.JFormattedTextField();
        btCadastro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSenha1 = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtTelefone1 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        pwSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(270, 443));
        jPanel1.setLayout(null);

        txtTelefone.setBackground(new java.awt.Color(0, 0, 0));
        txtTelefone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtTelefone.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelefone.setOpaque(false);
        txtTelefone.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusLost(evt);
            }
        });
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefone);
        txtTelefone.setBounds(70, 290, 130, 20);

        btCadastro.setText("Cadastre-se");
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(btCadastro);
        btCadastro.setBounds(80, 380, 110, 30);

        jLabel6.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Crie sua conta");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 120, 270, 50);

        txtSenha1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSenha1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSenha1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)));
        txtSenha1.setOpaque(false);
        txtSenha1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenha1FocusGained(evt);
            }
        });
        txtSenha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSenha1MouseClicked(evt);
            }
        });
        txtSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenha1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenha1);
        txtSenha1.setBounds(70, 330, 130, 30);

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)));
        txtUsuario.setOpaque(false);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(70, 170, 130, 30);

        txtTelefone1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelefone1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefone1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)));
        txtTelefone1.setOpaque(false);
        txtTelefone1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefone1FocusGained(evt);
            }
        });
        txtTelefone1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTelefone1MouseClicked(evt);
            }
        });
        txtTelefone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefone1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefone1);
        txtTelefone1.setBounds(70, 280, 130, 30);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)));
        txtEmail.setOpaque(false);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(70, 230, 130, 30);

        pwSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)));
        pwSenha.setOpaque(false);
        pwSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwSenhaFocusLost(evt);
            }
        });
        pwSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(pwSenha);
        pwSenha.setBounds(70, 330, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TelaInicial.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(260, 443));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 260, 443);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 260, 440);

        setSize(new java.awt.Dimension(259, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pwSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwSenhaActionPerformed

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed
        if (txtUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Digite um nome de USUÁRIO.");
        } else {
            if (txtEmail.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Digite um E-mail válido.");
            } else {
                if (txtTelefone.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "Digite um TELEFONE válido.");
                } else {
                    if (new String(pwSenha.getPassword()).isEmpty()) {
                        JOptionPane.showMessageDialog(rootPane, "Digite uma SENHA.");
                    }
                }
            }
        }

        try {
            confirmaUsuario(txtEmail.getText());
        } catch (Exception ex) {
            Logger.getLogger(TelaNovaConta.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (txtEmail.getText().equals(null)) {
            JOptionPane.showMessageDialog(rootPane, "Digite outro E-mail");
        } else {
            if (txtEmail.getText().equals("E-mail")) {
                JOptionPane.showMessageDialog(rootPane, "Digite outro E-mail");
            } else {
                if (txtEmail.getText().equals(email)) {
                    JOptionPane.showMessageDialog(rootPane, "Digite outro E-mail");
                } else {
                    try {
                        addUsuario(String.valueOf(pwSenha.getPassword()), txtEmail.getText(), TipoUsu);
                    } catch (Exception ex) {
                        Logger.getLogger(TelaNovaConta.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    try {
                        idUsuario(txtEmail.getText());
                    } catch (Exception ex) {
                        Logger.getLogger(TelaNovaConta.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    try {
                        addCliente(txtTelefone.getText(), txtUsuario.getText(), idUsu);
                    } catch (Exception ex) {
                        Logger.getLogger(TelaNovaConta.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    this.dispose();
                }
            }
        }


    }//GEN-LAST:event_btCadastroActionPerformed

    public void confirmaUsuario(String Conta) throws Exception {
        Conexao con = new Conexao();
        con.getConexao();

        String txtSQL = "";

        txtSQL = "select Email from tb_Usuario where Email = '" + Conta + "';";

        Statement banco = (Statement) Conexao.conexao.createStatement();
        ResultSet result = banco.executeQuery(txtSQL);

        while (result.next()) {
            email = result.getString("Email");
        }
    }

    public void addUsuario(String Senha,
            String Email,
            int Tipos
    ) throws Exception {

        Conexao con = new Conexao();
        con.getConexao();

        String txtSQL = "";

        txtSQL = "insert into tb_Usuario (Senha , Email , Data_Cadastro , idTipo_Usu) "
                + " Values ('" + Senha + "','" + Email + "', current_timestamp() ,'" + Tipos + "');";
        Statement banco = (Statement) Conexao.conexao.createStatement();
        int result = banco.executeUpdate(txtSQL);

    }

    public void addCliente(String Tel,
            String Nome,
            int Tipos) throws Exception {

        Conexao con = new Conexao();
        con.getConexao();

        String txtSQL = "";

        txtSQL = " Update tb_Cliente "
                + "set Telefone = '" + Tel + "', "
                + "Nome = '" + Nome + "' "
                + "Where 1 = 1 "
                + "and  idUsuario = '" + Tipos + "';";

        Statement banco = (Statement) Conexao.conexao.createStatement();
        int result = banco.executeUpdate(txtSQL);
    }

    public void idUsuario(String Email) throws Exception {

        Conexao con = new Conexao();
        con.getConexao();

        String txtSQL = "";

        txtSQL = "select max(idUsuario) as idUsuario from tb_Usuario where Email = '" + Email + "';";

        Statement banco = (Statement) Conexao.conexao.createStatement();
        ResultSet result = banco.executeQuery(txtSQL);

        while (result.next()) {
            idUsu = result.getInt("idUsuario");
        }
    }


    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtTelefone1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefone1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefone1MouseClicked

    private void txtTelefone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefone1ActionPerformed

    private void txtSenha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenha1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenha1MouseClicked

    private void txtSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenha1ActionPerformed

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if (txtUsuario.getText().equals("Usuário")) {
            if (txtUsuario.getForeground() == Color.GRAY) {
                txtUsuario.setText("");
                txtUsuario.setForeground(Color.BLACK);
            }
        }
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if (txtEmail.getText().equals("E-mail")) {
            if (txtEmail.getForeground() == Color.GRAY) {
                txtEmail.setText("");
                txtEmail.setForeground(Color.BLACK);
            }
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtTelefone1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefone1FocusGained
        if (txtTelefone1.getText().equals("Telefone")) {
            if (txtTelefone1.getForeground() == Color.gray) {
                txtTelefone1.setVisible(false);
                txtTelefone.setVisible(true);
                txtTelefone.requestFocus();

            }
        }

    }//GEN-LAST:event_txtTelefone1FocusGained

    private void txtSenha1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenha1FocusGained
        if (txtSenha1.getText().equals("Senha")) {
            if (txtSenha1.getForeground() == Color.GRAY) {
                txtSenha1.setVisible(false);
                pwSenha.setVisible(true);
                pwSenha.requestFocus();
            }
        }
    }//GEN-LAST:event_txtSenha1FocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if (txtUsuario.getText().equals("")) {
            txtUsuario.setText("Usuário");
            txtUsuario.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (txtEmail.getText().equals("")) {
            txtEmail.setText("E-mail");
            txtEmail.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void pwSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwSenhaFocusLost
        if (String.valueOf(pwSenha.getPassword()).isEmpty()) {
            txtSenha1.setVisible(true);

        }
    }//GEN-LAST:event_pwSenhaFocusLost

    private void txtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusLost
        if (txtTelefone.getText().equals("(##) #####-####")) {
            txtTelefone.setVisible(false);
            txtTelefone1.setVisible(true);
        }

    }//GEN-LAST:event_txtTelefoneFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovaConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pwSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSenha1;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtTelefone1;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
